export default {
  ADD_ENTITIES: 'ADD_ENTITIES',
  REPLACE_ENTITIES: 'REPLACE_ENTITIES',
  LOADING: 'LOADING',
  UPDATE_PAGER: 'PAGER',
  UPDATE_FILTERS: 'UPDATE_FILTERS',
  INITIALIZE_FILTERS: 'INITIALIZE_FILTERS'
};
